root - INFO - GA Tuner Matrix Multiplication - 2023-07-25 15:25:35.538033
autotvm - DEBUG - waiting for device...
autotvm - DEBUG - device available
autotvm - INFO - Get devices for measurement successfully!
autotvm - DEBUG - No: 1	GFLOPS: 0.00/0.00	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_x', 5), ('tile_xT', 1)],None,3
autotvm - DEBUG - No: 2	GFLOPS: 0.00/0.00	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_x', 10), ('tile_xT', 1)],None,5
autotvm - DEBUG - No: 3	GFLOPS: 3.01/3.01	result: MeasureResult(costs=(42.489545654000004,), error_no=MeasureErrorNo.NO_ERROR, all_cost=85.94893050193787, timestamp=1690317230.220399)	[('tile_x', 50), ('tile_xT', 1)],None,10
autotvm - DEBUG - No: 4	GFLOPS: 2.45/3.01	result: MeasureResult(costs=(52.27901455,), error_no=MeasureErrorNo.NO_ERROR, all_cost=105.20498919487, timestamp=1690317335.4709046)	[('tile_x', 80), ('tile_xT', 1)],None,11
autotvm - DEBUG - No: 5	GFLOPS: 2.55/3.01	result: MeasureResult(costs=(50.235027783999996,), error_no=MeasureErrorNo.NO_ERROR, all_cost=101.68734574317932, timestamp=1690317436.580168)	[('tile_x', 100), ('tile_xT', 1)],None,12
autotvm - DEBUG - No: 6	GFLOPS: 2.35/3.01	result: MeasureResult(costs=(54.358146983,), error_no=MeasureErrorNo.NO_ERROR, all_cost=109.98484468460083, timestamp=1690317546.2910814)	[('tile_x', 250), ('tile_xT', 1)],None,15
autotvm - DEBUG - No: 7	GFLOPS: 2.46/3.01	result: MeasureResult(costs=(51.991862606000005,), error_no=MeasureErrorNo.NO_ERROR, all_cost=106.53748416900635, timestamp=1690317652.1811073)	[('tile_x', 500), ('tile_xT', 1)],None,17
autotvm - DEBUG - No: 8	GFLOPS: 3.26/3.26	result: MeasureResult(costs=(39.240322217,), error_no=MeasureErrorNo.NO_ERROR, all_cost=76.43902611732483, timestamp=1690317728.043731)	[('tile_x', 2000), ('tile_xT', 1)],None,19
autotvm - DEBUG - No: 9	GFLOPS: 0.00/3.26	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_x', 1), ('tile_xT', 2)],None,20
autotvm - DEBUG - No: 10	GFLOPS: 2.48/3.26	result: MeasureResult(costs=(51.523381493,), error_no=MeasureErrorNo.NO_ERROR, all_cost=104.2976725101471, timestamp=1690318032.1684313)	[('tile_x', 20), ('tile_xT', 2)],None,27
autotvm - DEBUG - No: 11	GFLOPS: 3.77/3.77	result: MeasureResult(costs=(33.973484365,), error_no=MeasureErrorNo.NO_ERROR, all_cost=68.72361469268799, timestamp=1690318100.2868922)	[('tile_x', 40), ('tile_xT', 2)],None,29
autotvm - DEBUG - No: 12	GFLOPS: 3.27/3.77	result: MeasureResult(costs=(39.157669026,), error_no=MeasureErrorNo.NO_ERROR, all_cost=80.11167597770691, timestamp=1690318179.7187908)	[('tile_x', 80), ('tile_xT', 2)],None,31
autotvm - DEBUG - No: 13	GFLOPS: 3.21/3.77	result: MeasureResult(costs=(39.888553542000004,), error_no=MeasureErrorNo.NO_ERROR, all_cost=81.39490723609924, timestamp=1690318260.5554013)	[('tile_x', 100), ('tile_xT', 2)],None,32
autotvm - DEBUG - No: 14	GFLOPS: 3.50/3.77	result: MeasureResult(costs=(36.553951816,), error_no=MeasureErrorNo.NO_ERROR, all_cost=74.19832229614258, timestamp=1690318334.174899)	[('tile_x', 200), ('tile_xT', 2)],None,34
autotvm - DEBUG - No: 15	GFLOPS: 3.43/3.77	result: MeasureResult(costs=(37.300733271999995,), error_no=MeasureErrorNo.NO_ERROR, all_cost=74.48907423019409, timestamp=1690318408.223768)	[('tile_x', 250), ('tile_xT', 2)],None,35
autotvm - DEBUG - No: 16	GFLOPS: 4.43/4.43	result: MeasureResult(costs=(28.920447977,), error_no=MeasureErrorNo.NO_ERROR, all_cost=59.12198996543884, timestamp=1690318466.6400964)	[('tile_x', 1000), ('tile_xT', 2)],None,38
autotvm - DEBUG - No: 17	GFLOPS: 1.82/4.43	result: MeasureResult(costs=(70.164160103,), error_no=MeasureErrorNo.NO_ERROR, all_cost=141.7932686805725, timestamp=1690318608.0335748)	[('tile_x', 4), ('tile_xT', 4)],None,42
autotvm - DEBUG - No: 18	GFLOPS: 2.61/4.43	result: MeasureResult(costs=(49.11893295,), error_no=MeasureErrorNo.NO_ERROR, all_cost=102.66752195358276, timestamp=1690318710.7256472)	[('tile_x', 10), ('tile_xT', 4)],None,45
autotvm - DEBUG - No: 19	GFLOPS: 3.23/4.43	result: MeasureResult(costs=(39.638289354,), error_no=MeasureErrorNo.NO_ERROR, all_cost=80.83091306686401, timestamp=1690318791.044396)	[('tile_x', 20), ('tile_xT', 4)],None,47
autotvm - DEBUG - No: 20	GFLOPS: 4.71/4.71	result: MeasureResult(costs=(27.19807706,), error_no=MeasureErrorNo.NO_ERROR, all_cost=56.18501925468445, timestamp=1690318846.5003378)	[('tile_x', 50), ('tile_xT', 4)],None,50
autotvm - DEBUG - No: 21	GFLOPS: 3.79/4.71	result: MeasureResult(costs=(33.778754055,), error_no=MeasureErrorNo.NO_ERROR, all_cost=68.77586770057678, timestamp=1690318914.592853)	[('tile_x', 125), ('tile_xT', 4)],None,53
autotvm - DEBUG - No: 22	GFLOPS: 5.03/5.03	result: MeasureResult(costs=(25.42684358,), error_no=MeasureErrorNo.NO_ERROR, all_cost=52.04806852340698, timestamp=1690318966.6567445)	[('tile_x', 200), ('tile_xT', 4)],None,54
autotvm - DEBUG - No: 23	GFLOPS: 6.40/6.40	result: MeasureResult(costs=(20.013356872,), error_no=MeasureErrorNo.NO_ERROR, all_cost=41.06531047821045, timestamp=1690319007.7467868)	[('tile_x', 2000), ('tile_xT', 4)],None,59
autotvm - DEBUG - No: 24	GFLOPS: 1.97/6.40	result: MeasureResult(costs=(64.839976962,), error_no=MeasureErrorNo.NO_ERROR, all_cost=131.43055939674377, timestamp=1690319139.1696897)	[('tile_x', 2), ('tile_xT', 5)],None,61
autotvm - DEBUG - No: 25	GFLOPS: 2.80/6.40	result: MeasureResult(costs=(45.660198238999996,), error_no=MeasureErrorNo.NO_ERROR, all_cost=93.57005333900452, timestamp=1690319232.3947878)	[('tile_x', 5), ('tile_xT', 5)],None,63
autotvm - DEBUG - No: 26	GFLOPS: 2.42/6.40	result: MeasureResult(costs=(52.897237128,), error_no=MeasureErrorNo.NO_ERROR, all_cost=107.48397374153137, timestamp=1690319339.419077)	[('tile_x', 8), ('tile_xT', 5)],None,64
autotvm - DEBUG - No: 27	GFLOPS: 4.49/6.40	result: MeasureResult(costs=(28.507544641,), error_no=MeasureErrorNo.NO_ERROR, all_cost=58.089861154556274, timestamp=1690319397.487513)	[('tile_x', 80), ('tile_xT', 5)],None,71
autotvm - DEBUG - No: 28	GFLOPS: 5.44/6.40	result: MeasureResult(costs=(23.534070438,), error_no=MeasureErrorNo.NO_ERROR, all_cost=48.41943073272705, timestamp=1690319445.2281475)	[('tile_x', 400), ('tile_xT', 5)],None,76
autotvm - DEBUG - No: 29	GFLOPS: 2.47/6.40	result: MeasureResult(costs=(51.890498237,), error_no=MeasureErrorNo.NO_ERROR, all_cost=105.6856780052185, timestamp=1690319550.230865)	[('tile_x', 2), ('tile_xT', 10)],None,81
autotvm - DEBUG - No: 30	GFLOPS: 3.92/6.40	result: MeasureResult(costs=(32.683697724,), error_no=MeasureErrorNo.NO_ERROR, all_cost=66.84744620323181, timestamp=1690319616.7072911)	[('tile_x', 10), ('tile_xT', 10)],None,85
autotvm - DEBUG - No: 31	GFLOPS: 3.13/6.40	result: MeasureResult(costs=(40.954313817,), error_no=MeasureErrorNo.NO_ERROR, all_cost=83.09349226951599, timestamp=1690319699.6394398)	[('tile_x', 8), ('tile_xT', 13)],None,104
autotvm - DEBUG - No: 32	GFLOPS: 2.81/6.40	result: MeasureResult(costs=(45.556797197,), error_no=MeasureErrorNo.NO_ERROR, all_cost=94.75261735916138, timestamp=1690319793.806411)	[('tile_x', 16), ('tile_xT', 13)],None,106
autotvm - DEBUG - No: 33	GFLOPS: 6.85/6.85	result: MeasureResult(costs=(18.691204257000003,), error_no=MeasureErrorNo.NO_ERROR, all_cost=39.18027210235596, timestamp=1690319832.458655)	[('tile_x', 400), ('tile_xT', 13)],None,116
autotvm - DEBUG - No: 34	GFLOPS: 6.95/6.95	result: MeasureResult(costs=(18.411452896,), error_no=MeasureErrorNo.NO_ERROR, all_cost=38.11492729187012, timestamp=1690319870.4955204)	[('tile_x', 500), ('tile_xT', 13)],None,117
autotvm - DEBUG - No: 35	GFLOPS: 7.47/7.47	result: MeasureResult(costs=(17.146326884999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=35.56401801109314, timestamp=1690319906.0408509)	[('tile_x', 1000), ('tile_xT', 13)],None,118
autotvm - DEBUG - No: 36	GFLOPS: 7.68/7.68	result: MeasureResult(costs=(16.667357056,), error_no=MeasureErrorNo.NO_ERROR, all_cost=34.619216442108154, timestamp=1690319940.6105316)	[('tile_x', 2000), ('tile_xT', 13)],None,119
autotvm - DEBUG - No: 37	GFLOPS: 2.38/7.68	result: MeasureResult(costs=(53.85360585,), error_no=MeasureErrorNo.NO_ERROR, all_cost=109.44511651992798, timestamp=1690320049.5271342)	[('tile_x', 1), ('tile_xT', 20)],None,120
autotvm - DEBUG - No: 38	GFLOPS: 2.51/7.68	result: MeasureResult(costs=(50.914657181,), error_no=MeasureErrorNo.NO_ERROR, all_cost=103.27077913284302, timestamp=1690320152.7901723)	[('tile_x', 2), ('tile_xT', 20)],None,121
autotvm - DEBUG - No: 39	GFLOPS: 4.22/7.68	result: MeasureResult(costs=(30.332650280000003,), error_no=MeasureErrorNo.NO_ERROR, all_cost=61.801629304885864, timestamp=1690320214.5160027)	[('tile_x', 8), ('tile_xT', 20)],None,124
autotvm - DEBUG - No: 40	GFLOPS: 7.54/7.68	result: MeasureResult(costs=(16.986589585,), error_no=MeasureErrorNo.NO_ERROR, all_cost=35.67609786987305, timestamp=1690320249.7054064)	[('tile_x', 200), ('tile_xT', 20)],None,134
autotvm - DEBUG - No: 41	GFLOPS: 7.08/7.68	result: MeasureResult(costs=(18.075142735,), error_no=MeasureErrorNo.NO_ERROR, all_cost=37.689168214797974, timestamp=1690320286.8112738)	[('tile_x', 400), ('tile_xT', 20)],None,136
autotvm - DEBUG - No: 42	GFLOPS: 8.12/8.12	result: MeasureResult(costs=(15.76843902,), error_no=MeasureErrorNo.NO_ERROR, all_cost=33.33141899108887, timestamp=1690320320.1096406)	[('tile_x', 2000), ('tile_xT', 20)],None,139
autotvm - DEBUG - No: 43	GFLOPS: 2.75/8.12	result: MeasureResult(costs=(46.540810261,), error_no=MeasureErrorNo.NO_ERROR, all_cost=93.86660933494568, timestamp=1690320414.0068004)	[('tile_x', 2), ('tile_xT', 25)],None,141
autotvm - DEBUG - No: 44	GFLOPS: 4.86/8.12	result: MeasureResult(costs=(26.347798679,), error_no=MeasureErrorNo.NO_ERROR, all_cost=54.05047273635864, timestamp=1690320468.0309207)	[('tile_x', 25), ('tile_xT', 25)],None,148
autotvm - DEBUG - No: 45	GFLOPS: 7.59/8.12	result: MeasureResult(costs=(16.872365176,), error_no=MeasureErrorNo.NO_ERROR, all_cost=35.032246112823486, timestamp=1690320503.0649385)	[('tile_x', 250), ('tile_xT', 25)],None,155
autotvm - DEBUG - No: 46	GFLOPS: 5.00/8.12	result: MeasureResult(costs=(25.604613881000002,), error_no=MeasureErrorNo.NO_ERROR, all_cost=52.875957012176514, timestamp=1690320555.664859)	[('tile_x', 25), ('tile_xT', 40)],None,168
autotvm - DEBUG - No: 47	GFLOPS: 9.25/9.25	result: MeasureResult(costs=(13.842264756,), error_no=MeasureErrorNo.NO_ERROR, all_cost=28.81718397140503, timestamp=1690320584.249293)	[('tile_x', 40), ('tile_xT', 40)],None,169
autotvm - DEBUG - No: 48	GFLOPS: 9.44/9.44	result: MeasureResult(costs=(13.561268585,), error_no=MeasureErrorNo.NO_ERROR, all_cost=28.965951681137085, timestamp=1690320612.466527)	[('tile_x', 50), ('tile_xT', 40)],None,170
autotvm - DEBUG - No: 49	GFLOPS: 7.82/9.44	result: MeasureResult(costs=(16.372820124,), error_no=MeasureErrorNo.NO_ERROR, all_cost=33.972039222717285, timestamp=1690320646.4519165)	[('tile_x', 100), ('tile_xT', 40)],None,172
autotvm - DEBUG - No: 50	GFLOPS: 7.90/9.44	result: MeasureResult(costs=(16.199475026,), error_no=MeasureErrorNo.NO_ERROR, all_cost=33.74557042121887, timestamp=1690320680.177982)	[('tile_x', 2000), ('tile_xT', 40)],None,179
autotvm - DEBUG - No: 51	GFLOPS: 4.09/9.44	result: MeasureResult(costs=(31.284051578,), error_no=MeasureErrorNo.NO_ERROR, all_cost=63.78661775588989, timestamp=1690320743.8482022)	[('tile_x', 16), ('tile_xT', 50)],None,186
autotvm - DEBUG - No: 52	GFLOPS: 8.04/9.44	result: MeasureResult(costs=(15.914005044,), error_no=MeasureErrorNo.NO_ERROR, all_cost=33.04207897186279, timestamp=1690320776.8687537)	[('tile_x', 250), ('tile_xT', 50)],None,195
autotvm - DEBUG - No: 53	GFLOPS: 7.67/9.44	result: MeasureResult(costs=(16.689346256,), error_no=MeasureErrorNo.NO_ERROR, all_cost=34.547158002853394, timestamp=1690320811.407904)	[('tile_x', 400), ('tile_xT', 50)],None,196
autotvm - DEBUG - No: 54	GFLOPS: 7.94/9.44	result: MeasureResult(costs=(16.11486283,), error_no=MeasureErrorNo.NO_ERROR, all_cost=33.53719687461853, timestamp=1690320844.8844135)	[('tile_x', 2000), ('tile_xT', 50)],None,199
autotvm - DEBUG - No: 55	GFLOPS: 1.75/9.44	result: MeasureResult(costs=(73.240983716,), error_no=MeasureErrorNo.NO_ERROR, all_cost=147.69148707389832, timestamp=1690320992.0857077)	[('tile_x', 1), ('tile_xT', 52)],None,200
autotvm - DEBUG - No: 56	GFLOPS: 3.78/9.44	result: MeasureResult(costs=(33.878044013,), error_no=MeasureErrorNo.NO_ERROR, all_cost=68.79396486282349, timestamp=1690321060.8882349)	[('tile_x', 10), ('tile_xT', 52)],None,205
autotvm - DEBUG - No: 57	GFLOPS: 6.06/9.44	result: MeasureResult(costs=(21.131889101000002,), error_no=MeasureErrorNo.NO_ERROR, all_cost=43.582205295562744, timestamp=1690321104.4521675)	[('tile_x', 100), ('tile_xT', 52)],None,212
autotvm - DEBUG - No: 58	GFLOPS: 7.19/9.44	result: MeasureResult(costs=(17.809416699,), error_no=MeasureErrorNo.NO_ERROR, all_cost=36.48470330238342, timestamp=1690321140.9673707)	[('tile_x', 200), ('tile_xT', 52)],None,214
autotvm - DEBUG - No: 59	GFLOPS: 7.44/9.44	result: MeasureResult(costs=(17.200829266,), error_no=MeasureErrorNo.NO_ERROR, all_cost=35.2511351108551, timestamp=1690321176.2088761)	[('tile_x', 400), ('tile_xT', 52)],None,216
autotvm - DEBUG - No: 60	GFLOPS: 4.14/9.44	result: MeasureResult(costs=(30.920269414,), error_no=MeasureErrorNo.NO_ERROR, all_cost=62.92461705207825, timestamp=1690321238.9844146)	[('tile_x', 4), ('tile_xT', 100)],None,222
autotvm - DEBUG - No: 61	GFLOPS: 7.57/9.44	result: MeasureResult(costs=(16.911897469,), error_no=MeasureErrorNo.NO_ERROR, all_cost=35.23419809341431, timestamp=1690321274.0521631)	[('tile_x', 1000), ('tile_xT', 100)],None,238
autotvm - DEBUG - No: 62	GFLOPS: 6.80/9.44	result: MeasureResult(costs=(18.830535596,), error_no=MeasureErrorNo.NO_ERROR, all_cost=38.90632510185242, timestamp=1690321312.94499)	[('tile_x', 40), ('tile_xT', 104)],None,249
autotvm - DEBUG - No: 63	GFLOPS: 6.08/9.44	result: MeasureResult(costs=(21.049419884,), error_no=MeasureErrorNo.NO_ERROR, all_cost=43.20210313796997, timestamp=1690321356.1783352)	[('tile_x', 80), ('tile_xT', 104)],None,251
autotvm - DEBUG - No: 64	GFLOPS: 7.11/9.44	result: MeasureResult(costs=(18.00825634,), error_no=MeasureErrorNo.NO_ERROR, all_cost=36.6783561706543, timestamp=1690321392.8660405)	[('tile_x', 125), ('tile_xT', 104)],None,253
autotvm - DEBUG - No: 65	GFLOPS: 7.17/9.44	result: MeasureResult(costs=(17.864016922999998,), error_no=MeasureErrorNo.NO_ERROR, all_cost=36.65785241127014, timestamp=1690321429.527499)	[('tile_x', 400), ('tile_xT', 104)],None,256
autotvm - DEBUG - No: 66	GFLOPS: 2.99/9.44	result: MeasureResult(costs=(42.822332043,), error_no=MeasureErrorNo.NO_ERROR, all_cost=86.76195287704468, timestamp=1690321516.2764087)	[('tile_x', 2), ('tile_xT', 200)],None,261
autotvm - DEBUG - No: 67	GFLOPS: 4.77/9.44	result: MeasureResult(costs=(26.844872564000003,), error_no=MeasureErrorNo.NO_ERROR, all_cost=53.69567275047302, timestamp=1690321569.954815)	[('tile_x', 16), ('tile_xT', 200)],None,266
autotvm - DEBUG - No: 68	GFLOPS: 5.01/9.44	result: MeasureResult(costs=(25.525579664000002,), error_no=MeasureErrorNo.NO_ERROR, all_cost=52.31374931335449, timestamp=1690321622.2680688)	[('tile_x', 20), ('tile_xT', 200)],None,267
autotvm - DEBUG - No: 69	GFLOPS: 7.35/9.44	result: MeasureResult(costs=(17.40814184,), error_no=MeasureErrorNo.NO_ERROR, all_cost=36.183440923690796, timestamp=1690321658.437533)	[('tile_x', 125), ('tile_xT', 200)],None,273
autotvm - DEBUG - No: 70	GFLOPS: 7.56/9.44	result: MeasureResult(costs=(16.937697326000002,), error_no=MeasureErrorNo.NO_ERROR, all_cost=35.11362099647522, timestamp=1690321693.5772574)	[('tile_x', 1000), ('tile_xT', 200)],None,278
autotvm - DEBUG - No: 71	GFLOPS: 8.03/9.44	result: MeasureResult(costs=(15.949495193,), error_no=MeasureErrorNo.NO_ERROR, all_cost=33.12831974029541, timestamp=1690321726.714407)	[('tile_x', 2000), ('tile_xT', 200)],None,279
autotvm - DEBUG - No: 72	GFLOPS: 6.78/9.44	result: MeasureResult(costs=(18.883474205,), error_no=MeasureErrorNo.NO_ERROR, all_cost=38.99099087715149, timestamp=1690321765.7342317)	[('tile_x', 40), ('tile_xT', 260)],None,289
autotvm - DEBUG - No: 73	GFLOPS: 7.21/9.44	result: MeasureResult(costs=(17.753040823,), error_no=MeasureErrorNo.NO_ERROR, all_cost=37.06124544143677, timestamp=1690321802.8056586)	[('tile_x', 250), ('tile_xT', 260)],None,295
autotvm - DEBUG - No: 74	GFLOPS: 6.37/9.44	result: MeasureResult(costs=(20.100990244000002,), error_no=MeasureErrorNo.NO_ERROR, all_cost=41.577423334121704, timestamp=1690321844.0593827)	[('tile_x', 400), ('tile_xT', 260)],None,296
autotvm - DEBUG - No: 75	GFLOPS: 7.92/9.44	result: MeasureResult(costs=(16.171262349,), error_no=MeasureErrorNo.NO_ERROR, all_cost=33.274696588516235, timestamp=1690321877.3368216)	[('tile_x', 2000), ('tile_xT', 260)],None,299
autotvm - DEBUG - No: 76	GFLOPS: 1.95/9.44	result: MeasureResult(costs=(65.506133474,), error_no=MeasureErrorNo.NO_ERROR, all_cost=131.18963146209717, timestamp=1690322008.5304112)	[('tile_x', 2), ('tile_xT', 325)],None,301
autotvm - DEBUG - No: 77	GFLOPS: 3.03/9.44	result: MeasureResult(costs=(42.252838439,), error_no=MeasureErrorNo.NO_ERROR, all_cost=88.86449813842773, timestamp=1690322097.4025369)	[('tile_x', 5), ('tile_xT', 325)],None,303
autotvm - DEBUG - No: 78	GFLOPS: 6.56/9.44	result: MeasureResult(costs=(19.499511505999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=39.89374661445618, timestamp=1690322137.303277)	[('tile_x', 40), ('tile_xT', 325)],None,309
autotvm - DEBUG - No: 79	GFLOPS: 5.23/9.44	result: MeasureResult(costs=(24.466203428,), error_no=MeasureErrorNo.NO_ERROR, all_cost=49.553175926208496, timestamp=1690322186.513143)	[('tile_x', 80), ('tile_xT', 325)],None,311
autotvm - DEBUG - No: 80	GFLOPS: 5.61/9.44	result: MeasureResult(costs=(22.826552471,), error_no=MeasureErrorNo.NO_ERROR, all_cost=47.09157943725586, timestamp=1690322233.613788)	[('tile_x', 125), ('tile_xT', 325)],None,313
autotvm - DEBUG - No: 81	GFLOPS: 7.84/9.44	result: MeasureResult(costs=(16.320150427,), error_no=MeasureErrorNo.NO_ERROR, all_cost=33.55908131599426, timestamp=1690322267.1923294)	[('tile_x', 2000), ('tile_xT', 325)],None,319
autotvm - DEBUG - No: 82	GFLOPS: 5.62/9.44	result: MeasureResult(costs=(22.763980791999998,), error_no=MeasureErrorNo.NO_ERROR, all_cost=46.46736764907837, timestamp=1690322313.59109)	[('tile_x', 40), ('tile_xT', 520)],None,329
autotvm - DEBUG - No: 83	GFLOPS: 7.46/9.44	result: MeasureResult(costs=(17.165631586,), error_no=MeasureErrorNo.NO_ERROR, all_cost=36.2453453540802, timestamp=1690322349.2422051)	[('tile_x', 1000), ('tile_xT', 520)],None,338
autotvm - DEBUG - No: 84	GFLOPS: 0.00/9.44	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_x', 1), ('tile_xT', 650)],None,340
autotvm - DEBUG - No: 85	GFLOPS: 1.95/9.44	result: MeasureResult(costs=(65.544364946,), error_no=MeasureErrorNo.NO_ERROR, all_cost=131.95717096328735, timestamp=1690322681.4995255)	[('tile_x', 4), ('tile_xT', 650)],None,342
autotvm - DEBUG - No: 86	GFLOPS: 2.06/9.44	result: MeasureResult(costs=(62.008095606000005,), error_no=MeasureErrorNo.NO_ERROR, all_cost=125.02815532684326, timestamp=1690322806.4567645)	[('tile_x', 5), ('tile_xT', 650)],None,343
autotvm - DEBUG - No: 87	GFLOPS: 2.54/9.44	result: MeasureResult(costs=(50.396163282,), error_no=MeasureErrorNo.NO_ERROR, all_cost=102.10357308387756, timestamp=1690322908.4454951)	[('tile_x', 16), ('tile_xT', 650)],None,346
autotvm - DEBUG - No: 88	GFLOPS: 4.11/9.44	result: MeasureResult(costs=(31.142482694999998,), error_no=MeasureErrorNo.NO_ERROR, all_cost=63.75059962272644, timestamp=1690322972.1813731)	[('tile_x', 50), ('tile_xT', 650)],None,350
autotvm - DEBUG - No: 89	GFLOPS: 5.40/9.44	result: MeasureResult(costs=(23.706117284,), error_no=MeasureErrorNo.NO_ERROR, all_cost=48.99518322944641, timestamp=1690323020.9751337)	[('tile_x', 100), ('tile_xT', 650)],None,352
autotvm - DEBUG - No: 90	GFLOPS: 0.00/9.44	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_x', 2), ('tile_xT', 1300)],None,361
autotvm - DEBUG - No: 91	GFLOPS: 0.00/9.44	result: Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 742, in __call__
    yield remote, remote.load_module(os.path.split(build_result.filename)[1])
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 706, in run_through_rpc
    costs = time_f(*args).results
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 357, in evaluator
    blob = feval(*args)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 331, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  3: TVMFuncCall
  2: tvm::runtime::RPCWrappedFunc::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  1: tvm::runtime::RPCClientSession::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)> const&)
  0: tvm::runtime::RPCEndpoint::CallFunc(void*, TVMValue const*, int const*, int, std::function<void (tvm::runtime::TVMArgs)>)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 804
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=kShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 671, in run_through_rpc
    with module_loader(remote_kwargs, build_result) as (remote, mod):
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/autotvm/measure/measure_methods.py", line 746, in __call__
    remote.remove(build_result.filename)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 144, in remove
    self._remote_funcs["remove"] = self.get_function("tvm.rpc.server.remove")
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/rpc/client.py", line 72, in get_function
    return self._sess.get_function(name)
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/runtime/module.py", line 169, in get_function
    check_call(
  File "/home/pparamasivam/anaconda3/envs/tvm/lib/python3.10/site-packages/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  81: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  80: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  79: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  78: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  77: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  76: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  75: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  74: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  73: cfunction_vectorcall_FASTCALL
        at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
  72: builtin_exec
        at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
  71: builtin_exec_impl
        at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
  70: PyEval_EvalCode
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
  69: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  68: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  67: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  66: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  65: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  64: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  63: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  62: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  61: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  60: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
  59: do_call_core
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5943
  58: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  57: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  56: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  55: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4113
  54: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  53: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  52: method_vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
  51: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  50: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  49: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  48: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  47: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  46: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  45: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  44: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  43: method_vectorcall_VARARGS
        at /usr/local/src/conda/python-3.10.9/Objects/descrobject.c:311
  42: gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:571
  41: _gen_throw
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:549
  40: gen_send_ex
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:279
  39: gen_send_ex2
        at /usr/local/src/conda/python-3.10.9/Objects/genobject.c:213
  38: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  37: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  36: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  35: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  34: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  33: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  32: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  31: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  30: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  29: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  28: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  27: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  26: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  25: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  24: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  23: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
  22: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  21: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  20: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
  19: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  18: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  17: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  16: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
  15: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  14: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
  13: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
  12: _PyObject_VectorcallTstate
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
  11: _PyObject_MakeTpCall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:215
  10: PyCFuncPtr_call
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/_ctypes.c:4201
  9: _ctypes_callproc
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:1262
  8: _call_function_pointer
        at /usr/local/src/conda/python-3.10.9/Modules/_ctypes/callproc.c:916
  7: ffi_call
  6: ffi_call_int
  5: ffi_call_unix64
  4: TVMModGetFunction
  3: tvm::runtime::ModuleNode::GetFunction(std::string const&, bool) [clone .localalias]
  2: tvm::runtime::RPCModuleNode::GetFunction(std::string const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)
  1: tvm::runtime::RPCClientSession::GetFunction(std::string const&)
  0: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::RPCEndpoint::Init()::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  File "/workspace/tvm/src/runtime/rpc/rpc_endpoint.cc", line 684
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (code == RPCCode::kReturn) is false: code=1

Traceback (most recent call last):
  94: 0xffffffffffffffff
  93: 0x000000000058c1ed
  92: __libc_start_main
  91: Py_BytesMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
  90: Py_RunMain
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
  89: pymain_run_python
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:585
  88: pymain_run_module
        at /usr/local/src/conda/python-3.10.9/Modules/main.c:297
  87: _PyFunction_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
  86: _PyEval_Vector
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
  85: _PyEval_EvalFrame
        at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
  84: _PyEval_EvalFrameDefault
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
  83: call_function
        at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
  82: PyObject_Vectorcall
        at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:12	[('tile_x', 4), ('tile_xT', 1300)],None,362
autotvm - DEBUG - No: 92	GFLOPS: 1.44/9.44	result: MeasureResult(costs=(88.963252055,), error_no=MeasureErrorNo.NO_ERROR, all_cost=178.51372170448303, timestamp=1690323600.134)	[('tile_x', 5), ('tile_xT', 1300)],None,363
autotvm - DEBUG - No: 93	GFLOPS: 3.74/9.44	result: MeasureResult(costs=(34.192323856,), error_no=MeasureErrorNo.NO_ERROR, all_cost=69.50265383720398, timestamp=1690323669.6075652)	[('tile_x', 80), ('tile_xT', 1300)],None,371
autotvm - DEBUG - No: 94	GFLOPS: 5.78/9.44	result: MeasureResult(costs=(22.158712622,), error_no=MeasureErrorNo.NO_ERROR, all_cost=45.56902527809143, timestamp=1690323715.1509228)	[('tile_x', 200), ('tile_xT', 1300)],None,374
autotvm - DEBUG - No: 95	GFLOPS: 6.37/9.44	result: MeasureResult(costs=(20.108764255999997,), error_no=MeasureErrorNo.NO_ERROR, all_cost=41.48447513580322, timestamp=1690323756.5991447)	[('tile_x', 400), ('tile_xT', 1300)],None,376
autotvm - DEBUG - No: 96	GFLOPS: 6.50/9.44	result: MeasureResult(costs=(19.698216857,), error_no=MeasureErrorNo.NO_ERROR, all_cost=40.478142976760864, timestamp=1690323797.088235)	[('tile_x', 500), ('tile_xT', 1300)],None,377
autotvm - DEBUG - No: 97	GFLOPS: 2.08/9.44	result: MeasureResult(costs=(61.430762237,), error_no=MeasureErrorNo.NO_ERROR, all_cost=123.76377987861633, timestamp=1690323920.8123481)	[('tile_x', 16), ('tile_xT', 2600)],None,386
autotvm - DEBUG - No: 98	GFLOPS: 3.99/9.44	result: MeasureResult(costs=(32.115133310000004,), error_no=MeasureErrorNo.NO_ERROR, all_cost=65.32976222038269, timestamp=1690323986.0924172)	[('tile_x', 100), ('tile_xT', 2600)],None,392
autotvm - DEBUG - No: 99	GFLOPS: 3.67/9.44	result: MeasureResult(costs=(34.916678292,), error_no=MeasureErrorNo.NO_ERROR, all_cost=71.00058770179749, timestamp=1690324057.0947614)	[('tile_x', 125), ('tile_xT', 2600)],None,393
autotvm - DEBUG - No: 100	GFLOPS: 3.21/9.44	result: MeasureResult(costs=(39.902408218,), error_no=MeasureErrorNo.NO_ERROR, all_cost=80.88653683662415, timestamp=1690324137.938051)	[('tile_x', 1000), ('tile_xT', 2600)],None,398
root - INFO - Elpased time = 7401.848427534103
autotvm - DEBUG - Finish loading 100 records
